services:
  postgres:
    container_name: appointment-manager-postgres
    hostname: postgres
    image: postgres:18.6-alpine3.24
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  mailpit:
    container_name: appointment-manager-mailpit
    hostname: mailpit
    image: axllent/mailpit:v1.30.7
    ports:
      - "127.0.0.1:1025:1025"
      - "127.0.0.1:8025:8025"
    security_opt:
      - no-new-privileges:true

volumes:
  postgres_data:
    name: appointment-manager-postgres-data
