services:
  server:
    container_name: appointment-manager
    hostname: server
    image: git.sonuserver.com/fortega21/appointment-manager:latest
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
      ENV: production
    networks:
      - caddy_network
      - backend_network
    expose:
      - ${API_PORT:-8080}
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    depends_on:
      postgres:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

  postgres:
    container_name: appointment-manager-postgres
    hostname: postgres
    image: postgres:18.3-alpine3.23
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - backend_network
    expose:
      - ${POSTGRES_PORT:-5432}
    volumes:
      - postgres_data:/var/lib/postgresql
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G

volumes:
  postgres_data:
    name: appointment-manager-postgres-data

networks:
  caddy_network:
    external: true
  backend_network:
    internal: true
